export { default as PokemonDataImg } from "./pokemonDataImg/PokemonDataImg";
export { default as PokemonDataType } from "./pokemonDataType/PokemonDataType";
export { default as PokemonFlavor } from "./pokemonFlavor/PokemonFlavor";
export { default as PokemonDataAbility } from "./pokemonDataAbility/PokemonDataAbility";
export { default as PokemonDataStats } from "./pokemonDataStats/PokemonDataStats";
export { default as PokemonDataInfo } from "./pokemonDataInfo/PokemonDataInfo";
export { default as PokemonDataWeakness } from "./pokemonDataWeakness/PokemonDataWeakness";
export { default as PokemonDataEvolution } from "./pokemonDataEvolution/PokemonDataEvolution";
export { default as PokemonDataVarieties } from "./pokemonDataVarieties/PokemonDataVarieties";
