export const typeOptions = [
  { value: "", label: "No Type" },
  { value: "Normal", label: "Normal" },
  { value: "Fire", label: "Fire" },
  { value: "Grass", label: "Grass" },
  { value: "Flying", label: "Flying" },
  { value: "Fighting", label: "Fighting" },
  { value: "Poison", label: "Poison" },
  { value: "Electric", label: "Electric" },
  { value: "Ground", label: "Ground" },
  { value: "Rock", label: "Rock" },
  { value: "Psychic", label: "Psychic" },
  { value: "Ice", label: "Ice" },
  { value: "Bug", label: "Bug" },
  { value: "Ghost", label: "Ghost" },
  { value: "Steel", label: "Steel" },
  { value: "Dragon", label: "Dragon" },
  { value: "Dark", label: "Dark" },
  { value: "Fairy", label: "Fairy" },
];
